{% set name = "ossfs" %}
{% set version = "2023.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ossfs-{{ version }}.tar.gz
  sha256: 99df5b678c516bb24b56d5a54ad60b726f0b1989d6d89f893a471b3aa982f366

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm >=6.3.1
  run:
    - aiooss2 >=0.2.5
    - oss2 >=2.17.0
    - fsspec >=2023.4.0
    - python >=3.8

test:
  imports:
    - ossfs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ossfs/
  summary: ossfs fsspec filesystem for Alibaba Cloud (Aliyun) Object Storage System (OSS)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - karajan1001
    - efiop
