{% set name = "ossfs" %}
{% set version = "2023.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ossfs-{{ version }}.tar.gz
  sha256: da3c071eee26b17cd6a9dcf6e3fb162f67bf5946275204f3027ecff0fa935e24

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - oss2 >=2.6.1
    - fsspec >=2021.7.0
    - python >=3.6

test:
  imports:
    - ossfs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ossfs/
  summary: ossfs fsspec filesystem for Alibaba Cloud (Aliyun) Object Storage System (OSS)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - karajan1001
    - efiop
